name: fitness_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.8
  http: ^0.12.2
  sleek_circular_slider: ^1.1.0
  audioplayers: ^0.15.1
  circular_countdown_timer: ^0.0.4
  hexcolor: ^1.0.6
  firebase_admob: ^0.11.0+1
  firebase_core: ^0.7.0
  facebook_audience_network: ^0.8.0
  firebase_database: ^6.0.0
  unity_ads_plugin: ^0.1.2
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconspro.png"
  adaptive_icon_background: "assets/background1.png"
  adaptive_icon_foreground: "assets/foreground1.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins-Bold
       fonts:
           - asset: assets/Fonts/Poppins-Bold.ttf


     - family: Poppins-Regular
       fonts:
         - asset: assets/Fonts/Poppins-Regular.ttf


     - family: Poppins-Light
       fonts:
         - asset: assets/Fonts/Poppins-Light.ttf

     - family: ComicSansMS3
       fonts:
          - asset: assets/Fonts/ComicSansMS3.ttf

     - family: COMIC
       fonts:
             - asset: assets/Fonts/COMIC.TTF

     - family: comici
       fonts:
         - asset: assets/Fonts/comici.ttf

     - family: comicz
       fonts:
         - asset: assets/Fonts/comicz.ttf

     - family: design.graffiti.comicsansms
       fonts:
         - asset: assets/Fonts/design.graffiti.comicsansms.ttf
     - family: MontserratExtraBold
       fonts:
         - asset: assets/Fonts/Montserrat-ExtraBold.otf
     - family: MontserratSemiBold
       fonts:
          - asset: assets/Fonts/Montserrat-SemiBold.otf
     - family: DS-DIGI
       fonts:
         - asset: assets/Fonts/DS-DIGI.TTF

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
